version: "3.7"
services:
  db_postgress:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    env_file:
      - ".env"
    ports:
      - "5434:5432"
